sonar.sources=etcd-recipes/src/main,etcd-recipes-examples/src/main
#sonar.exclusions=
#sonar.inclusions=
# Path to tests
sonar.tests=etcd-recipes/src/test
#sonar.test.exclusions=
#sonar.test.inclusions=
# Source encoding
sonar.sourceEncoding=UTF-8
# Exclusions for copy-paste detection
#sonar.cpd.exclusions=
